spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:bithave_db}
    username: ${POSTGRES_USER:bithave_user}
    password: ${POSTGRES_PASSWORD:bithave_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.jdbc.core: INFO
    org.hibernate.SQL: DEBUG                 # zeigt SQL-Statements
    org.hibernate.orm.jdbc.bind: TRACE       # zeigt SQL-Parameter
