spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:bithave_db}  # Host = Service-Name
    username: ${POSTGRES_USER:bithave_user}
    password: ${POSTGRES_PASSWORD:bithave_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
